version: "3"

services:
  backend:
    image: ghcr.io/mathiasreker/demo-ksdfjsslfkja:latest
    ports:
      - "80:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqlDb:3307/kurt2?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true
      - spring.datasource.username=root
      - spring.datasource.password=kurt
      - spring.jpa.properties.hibernate.jdbc.time_zone=UTC
      - spring.jpa.hibernate.ddl-auto=update
    networks:
      - backend-net
    depends_on:
      - mysqlDb

  mysqlDb:
    image: mysql:8
    ports:
      - "3307:3306"
    networks:
      - backend-net
    environment:
      - MYSQL_ROOT_PASSWORD=kurt
      - MYSQL_DATABASE=kurt2

networks:
  backend-net: {}
