version: "3"

services:
  backend:
    image: ghcr.io/mathiasreker/demo-ksdfjsslfkja:latest
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/kurt?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true
      - spring.datasource.username=root
      - spring.datasource.password=kurt
      - spring.jpa.properties.hibernate.jdbc.time_zone=UTC
      - spring.jpa.hibernate.ddl-auto=update
    ports:
      - "80:80"
    networks:
      - backend-net
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    networks:
      - backend-net
    environment:
      - MYSQL_ROOT_PASSWORD=kurt
      - MYSQL_DATABASE=kurt

networks:
  backend-net:
