version: "3"

parameters:
  MYSQL_ROOT_PASSWORD: myrootpw
  MYSQL_DATABASE: mydb
  MYSQL_USER: myuser
  MYSQL_PASSWORD: mypw
  MYSQL_PORT: 3307
  DOCKER_IMAGE_NAME: demo-ksdfjsslfkja
  GITHUB_USER: mathiasreker #lowercase
  
services:
  backend:
    image: ghcr.io/${{ parameters.GITHUB_USER }}/${{ parameters.DOCKER_IMAGE_NAME }}:dev
    ports:
      - "80:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqlDb:${{ parameters.MYSQL_PORT }}/${{ parameters.MYSQL_DATABASE }}?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true
      - spring.datasource.username=${{ parameters.MYSQL_USER }}
      - spring.datasource.password=${{ parameters.MYSQL_PASSWORD }}
      - spring.jpa.properties.hibernate.jdbc.time_zone=UTC
      - spring.jpa.hibernate.ddl-auto=update
    networks:
      - backend-net
    depends_on:
      - mysqlDb

  mysqlDb:
    image: mysql:latest
    ports:
      - "${{ parameters.MYSQL_PORT }}:3306"
    networks:
      - backend-net
    environment:
      - MYSQL_ROOT_PASSWORD=${{ parameters.MYSQL_ROOT_PASSWORD }}
      - MYSQL_DATABASE=${{ parameters.MYSQL_DATABASE }}
      - MYSQL_USER=${{ parameters.MYSQL_USER }}
      - MYSQL_PASSWORD=${{ parameters.MYSQL_PASSWORD }}

networks:
  backend-net: {}
