version: "3"

parameters:
  MYSQL_ROOT_PASSWORD: myrootpw
  MYSQL_DATABASE: mydb
  MYSQL_USER: myuser
  MYSQL_PASSWORD: mypw
  MYSQL_HOST: mysqlDb  
  MYSQL_PORT: 3307  
  DOCKER_IMAGE_NAME: demo-ksdfjsslfkja  
  
services:
  backend:
    image: ghcr.io/mathiasreker/${{ parameters.DOCKER_IMAGE_NAME }}:dev
    ports:
      - "80:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqlDb:3307/kurt2?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true
      - spring.datasource.username=${{ parameters.MYSQL_ROOT_PASSWORD }}
      - spring.datasource.password=mypw
      - spring.jpa.properties.hibernate.jdbc.time_zone=UTC
      - spring.jpa.hibernate.ddl-auto=update
    networks:
      - backend-net
    depends_on:
      - mysqlDb

  mysqlDb:
    image: mysql:latest
    ports:
      - "3307:3306"
    networks:
      - backend-net
    environment:
      - MYSQL_ROOT_PASSWORD=myrootpw
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypw

networks:
  backend-net: {}
