name: Java CI with Maven

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B clean package -Dmaven.test.skip.exec
      - name: Unit Test
        run: mvn '-Dtest=com.example.githubactionmavenbuild.Test.*Test*' test
      - name: Integration Test
        run: mvn '-Dtest=com.example.githubactionmavenbuild.IT.*Test*' test
